name : Run ESLint
on : push
jobs :
    eslint :
        runs-on : ubuntu-latest
          steps :
              - uses : actions/setup-node@v2    
              - with : 
                  - node-version : '14.x'      
              -name : Install dependencies
                  - run : npm install      
              -name : Run Eslint
                  - run : npx eslint index.js
                  - run : node --version
                    
                    